[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  PRISMA_GENERATE = "true"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs" 